apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-12
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-12
    app.kubernetes.io/part-of: application-to-test-git-ops
  name: java-quarkus-12
  namespace: sbudhwar-1
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: java-quarkus-12
status:
  loadBalancer: {}
